Update zh-TW
SpriteOvO/AirPodsDesktop pull request #96
Opened 2023-10-14 06:16 UTC by Neo1102

improve apd_zh_TW.ts and add README.md for traditional chinese

2023-10-14 18:40 UTC, SpriteOvO requested changes
Appreciate your contribution to translations! I just found some minor issues, you can continue to commit changes on your branch to fix them.

2023-10-14 18:40 UTC, SpriteOvO commented on README.md
> +<p align="center">🌎 English </a>| 🌏 <a href="/README-TW.md">繁體中文</a> | 🌏 <a href="/README-CN.md">简体中文</a></p>
```suggestion
<p align="center">🌎 English | 🌏 <a href="/README-CN.md">简体中文</a> | 🌏 <a href="/README-TW.md">繁體中文</a></p>
```

The first newly added `</a>` seems unnecessary, and according to the alphabetical order, `zh_TW` should be better placed after `zh_CN`.

2023-10-14 18:40 UTC, SpriteOvO commented on README-CN.md
> +<p align="center">🌎 <a href="/README.md">English</a> | 🌏 <a href="/README-TW.md">繁體中文</a> | 🌏 简体中文</p>
```suggestion
<p align="center">🌎 <a href="/README.md">English</a> | 🌏 简体中文 | 🌏 <a href="/README-TW.md">繁體中文</a></p>
```

2023-10-14 18:40 UTC, SpriteOvO commented on README-TW.md
> +<p align="center">🌎 <a href="/README.md">English</a> | 🌏 繁體中文</a> | 🌏 <a href="/README-CN.md">简体中文</a></p>
```suggestion
<p align="center">🌎 <a href="/README.md">English</a> | 🌏 <a href="/README-CN.md">简体中文</a> | 🌏 繁體中文</p>
```

2023-10-14 18:40 UTC, SpriteOvO commented on README-TW.md
> +<p align="center">🌎 <a href="/README.md">English</a> | 🌏 繁體中文</a> | 🌏 <a href="/README-CN.md">简体中文</a></p>
Same, a unnecessary `</a>` and the order issue.

2023-10-14 18:43 UTC, SpriteOvO commented on README-TW.md
> +<p align="center"> AirPods 桌面使用者體驗增進軟體</p>
```suggestion
<p align="center">AirPods 桌面使用者體驗增進軟體</p>
```

2023-10-16 02:28 UTC, Neo1102 commented
Hi
I have confirmed that your modifications have been applied to my branch. Do I need to open a new pull request, or is there any step I might have missed?

2023-10-16 02:31 UTC, SpriteOvO commented
Oh, sorry. No more action is needed, I just forgot to process it yesterday. I will merge it today.

2023-10-16 04:53 UTC, merged

2023-10-16 04:54 UTC, SpriteOvO commented
Thanks for your contributions again!